### ISSUE TITLE
New Mode Update Owned Beans Issue

### ISSUE THREAD

**Issue by VeenitXSheth** [RuntimeTerror2021/play#1]
Since the new update where modes were added, all of my beans got reset. like i dont have any beans in my "owned beans" section. idk if its coz of localStorage issue that got reset, or if it happened to everyone.

btw dis vnut sheets

**Comment by RuntimeTerror2021** [comment]
Hey vnut sheets, 

Can you send screenshots? Nobody else has reported loss of all beans since the new addition of game modes. The cause of this may be that you cleared localStorage while trying to fix another issue. If the problem keeps recurring, please inform me and I will look into it. I will also be sure to watch others' devices to see if they are having the same issue. 
Thanks
